Objective: to implement the trading algorithms and reproduce the results
(specifically, Figures 8, 9, 10, 11, and 17) described in the following
paper: 
[[file:~/projects/finance/literature/AvellanedaLeeStatArb20090616.pdf][M. Avellaneda and J.-H. Lee. Statistical Arbitrage in the U.S. Equities Market.]]

My notes on the paper: 
[[file:~/projects/finance/notes/avellaneda-lee-paper-notes.jnt][(jnt file)]]

* Source data:
  CRSP-97-08.csv.gz  CRSP-97-08_etf.csv.gz  CRSP-97-08_etf_shrt.csv.gz
  Obtained from WRDS CRSP database using my reference universe (SPX tickers
  as of Nov 2008 plus a list of ETFs).
  Selected a bunch of fields, so need to filter out the relevant ones; on the
  most basic level only need TICKER, DATE, RET (period returns,
  i.e. returns with dividends correctly accounted for).

  Date range: 01Jul1996 - 30Jun2009
  Ticker list: [[file:~/projects/finance/spx_tickers_20081107.txt][SPX 20081107]] (~/projects/finance/spx_tickers_20081107.txt)
  ETF list: (file:~/projects/finance/ETF_master_tkrs.txt)

** Data generation: 100108
  Variables Selected:
  DATE,CUSIP,DCLRDT,PAYDT,RCRDDT,SHRFLG,TICKER,PERMNO,EXCHCD,NAICS,PRIMEXCH,TRDSTAT,SECSTAT,DISTCD,DIVAMT,FACPR,FACSHR,ACPERM,ACCOMP,SHROUT,BIDLO,ASKHI,PRC,VOL,RET,BID,ASK,CFACPR,CFACSHR,OPENPRC,SXRET,BXRET,NUMTRD,RETX,vwretd,vwretx,ewretd,ewretx,sprtrn
  Here we number them in emacs (via number-lines-region); 1-DATE; 7-TICKER; 25-RET; 
  :DETAILS:
 1. DATE
 2. CUSIP
 3. DCLRDT
 4. PAYDT
 5. RCRDDT
 6. SHRFLG
 7. TICKER
 8. PERMNO
 9. EXCHCD
10. NAICS
11. PRIMEXCH
12. TRDSTAT
13. SECSTAT
14. DISTCD
15. DIVAMT
16. FACPR
17. FACSHR
18. ACPERM
19. ACCOMP
20. SHROUT
21. BIDLO
22. ASKHI
23. PRC
24. VOL
25. RET
26. BID
27. ASK
28. CFACPR
29. CFACSHR
30. OPENPRC
31. SXRET
32. BXRET
33. NUMTRD
34. RETX
35. vwretd
36. vwretx
37. ewretd
38. ewretx
39. sprtrn
:END:

  #  Isolate the DATE, TICKER, RET fields via
  cut -d ',' -f 1,7,25 spx_data_full.csv > spx_data_ret.csv
  cut -d ',' -f 1,7,25 etf_data_full.csv > etf_data_ret.csv
  # 1669379 spx_data_ret.csv # num recs
  # 655064 etf_data_ret.csv  # num recs

** Data generation: 100109
   Decided to expand the stock universe by merging the Nov 2008 SPX ticker
   list with the Jun 2001 Russell 1000 and first half of Jun 2001 Russell
   2000 lists for a grand total of 2079 ticker symbols.  Also selected
   additional variables, among which is PERMCO to keep track of ticker
   renamings, etc
   Number them in emacs (via number-lines-region): 
   1-DATE; 9-TICKER; 28-RET; 
   10-PERMNO; 27-VOL
   Call the dataset "universe 1"
   :DETAILS:
 1. DATE
 2. HSICMG
 3. HSICIG
 4. CUSIP
 5. DCLRDT
 6. PAYDT
 7. RCRDDT
 8. SHRFLG
 9. TICKER
 10. PERMNO
 11. EXCHCD
 12. NAICS
 13. PRIMEXCH
 14. TRDSTAT
 15. SECSTAT
 16. PERMCO
 17. DISTCD
 18. DIVAMT
 19. FACPR
 20. FACSHR
 21. ACPERM
 22. ACCOMP
 23. SHROUT
 24. BIDLO
 25. ASKHI
 26. PRC
 27. VOL
 28. RET
 29. BID
 30. ASK
 31. CFACPR
 32. CFACSHR
 33. OPENPRC
 34. SXRET
 35. BXRET
 36. NUMTRD
 37. RETX
 38. vwretd
 39. vwretx
 40. ewretd
 41. ewretx
 42. sprtrn
   :END:
   #  Isolate the DATE, TICKER, RET fields via
   cut -d ',' -f 1,9,28 univ1_data_full.csv > univ1_data_ret.csv

*** ETF data as of 100109:
    Discovered that ETF data hasn't been regenerated using the latest set of
    fields/time periods; for now will stick to using it with the fields:
    1-DATE; 2-TICKER; 16-RET
    #  Isolate the DATE, TICKER, RET fields via
    cut -d ',' -f 1,2,16 etf_data_full.csv > etf_data_ret.csv
    :DETAILS:
 1. DATE
 2. TICKER
 3. PERMNO
 4. EXCHCD
 5. TRDSTAT
 6. SECSTAT
 7. DISTCD
 8. DIVAMT
 9. FACPR
10. FACSHR
11. SHROUT
12. BIDLO
13. ASKHI
14. PRC
15. VOL
16. RET
17. OPENPRC
18. SXRET
19. BXRET
20. NUMTRD
21. RETX
    :END:
*** ETF data as of 100110:
    Regenerated the ETF data, fields are (like in the latest stock data)
     1-DATE; 9-TICKER; 28-RET; 
    10-PERMNO; 27-VOL
    cut -d ',' -f 1,9,28 etf1_data_full.csv > etf_data_ret.csv
*** List of dates available in file dates_vec_090630
    when the full spx matrix was still loaded, did
    dates.vector <- as.numeric(row.names(spx.ret.mtx.full))
    write.csv(dates.vector,file="dates_vec_090630",row.names=F)
*** 15 ETFs from Table 3 and Table 4 of the paper:
    :DETAILS:
HHH
IYR
IYT
OIH
RKH
RTH
SMH
UTH
XLE
XLF
XLI
XLK
XLP
XLV
XLY
    :END:

** Data processing:
   Convert to a returns matrix sorted by date, ticker:
   # ./convert.py -i etf_data_ret.csv -o etf_old_ret_mtx
   ./convert.py -i etf_data_ret.csv -o etf_ret_mtx
   ./convert.py -i spx_data_ret.csv -o spx_ret_mtx
   ./convert.py -i univ1_data_ret.csv -o univ1_ret_mtx
   
   Correlation matrix: get rid of the tickers that have too many NAs
   proc_corr.r
